config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'static_pages/home'
  get 'static_pages/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home' 
  get '/about', to: "static_pages#about"
  get '/sign_up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy" 

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :email, presence: true
	validates :email, length: {maximum: 255, message: "Max is 255"},
	 format: {with: VALID_EMAIL_REGEX}, uniqueness: true
	validate :check_length_name, if: ->{ name.present? }
	has_secure_password
	
	
	def check_length_name
		if name.size > 150
			errors.add :name, "length maximum is 150"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include StaticPagesHelper
	include ApplicationHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by email: params[:session][:email].downcase
  	if @user.present? && @user.authenticate(params[:session][:password])
  		login_user @user 
  		flash[:sucess] = "Login sucessful"
  		redirect_to @user
  	else
  		flash.now[:danger] = "Email or Password incorrect!"
  		render :new
  	end
  end

  def destroy
  	session.delete(:user_id)
  	@current_user = nil
  	flash[:sucess] = "goodbye"
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :login?, only: [:show]

	def show
		@user = User.find_by id: params[ :id]
	end

	def new
		@user = User.new
	end

	def create
		#@user = User.new
		#render :new
		@user = User.new user_params
		if @user.save
			flash[:success] = "Create account Success!!"
			redirect_to @user
		else 
			flash.now[:danger] = "Error: Create account fail!!"
			render :new 
		end
	end

	private
	def user_params
		params.require(:user).permit :name, :email, :password, :password_confirmation
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_user user
		session[:user_id] = user.id
	end

	def current_user
		#@current_user = @current_user || User.find_by id: session[:user_id]
		@current_user ||= User.find_by id: session[:user_id]
	end

	def login? 
		return if current_user
			flash[:danger] ="Moi ban login"
			redirect_to login_path
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def full_title page_title =""    
		base_title ="Ruby on Rails Tutorial Sample App"    
		page_title.empty?? base_title : "#{page_title} | #{base_title}"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
	<% if @user.errors.any? %>
		<ul>
			<% @user.errors.full_messages.each do |msg|%>
			<li><%= msg%></li>		
			<% end %>		
		</ul>
	<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", about_url %></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <a href=""></a>
        <%= link_to "sample app","#", id:"logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home","#" %></li>
            <li><%= link_to "Help","#" %></li>
            <li><%= link_to "Log in","#" %></li>

            <% if current_user %>
              <li><% link_to "log out", logout_path, method: :delete%></li>
              <% else %>
              <li><% link_to "log in", login_path %></li>
            <% end%>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |type_msg, message| %>
        <div class="alert alert-<%= type_msg %>" role ="alert"><%= message %></div>
      <% end %>
      <%=yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About page </h1>

app/views/static_pages/help.html.erb
<% provide :title, "Help"%>
<h1>Help</h1>
<p>Get help on the Ruby on RailsTutorial at the<a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>
  .Toget help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>  
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<h1>Sample App</h1>
<p>
	This is the home page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial </a>  sample application.
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

			<%= render "layouts/error_messages"%>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :email %>
			<%= f.email_field :email %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
	<% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1>Welcome <%= @user.name%></h1>